name: clone-to-gh-docs

on:
    push:
        branches:
          - main

permissions:
    contents: write
    pull-requests: write

jobs:
    create-pr:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
                
            - uses: actions/setup-node@v4

            - run: git fetch

            - run: git pull

            - name: Clone to docs
              run: cp -rf ./2-html/* ./docs/

            - name: Showen the path
              run: pwd

            - name: Showen the item
              run: tree

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v8
              with:
                commit-message: "Update file"
                delete-branch: true
                title: "[Automated] Update file"
                body: "This is an automated PR to update the report file."
